//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndiaEvents2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loginHistory
    {
        public int ID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> loginHistory1 { get; set; }
        public byte[] authToken { get; set; }
        public string authTokens { get; set; }
    }
}
