//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndiaEvents2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupType
    {
        public LookupType()
        {
            this.Lookups = new HashSet<Lookup>();
        }
    
        public System.Guid lookupID { get; set; }
        public string lookupType1 { get; set; }
    
        public virtual ICollection<Lookup> Lookups { get; set; }
    }
}
