//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndiaEvents2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup
    {
        public int sno { get; set; }
        public System.Guid lookupID { get; set; }
        public string lookups { get; set; }
        public Nullable<System.Guid> lookupsId { get; set; }
    
        public virtual LookupType LookupType { get; set; }
    }
}
