//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndiaEvents2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int sno { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
    }
}
